In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
def cust_name():
    names = soup.find_all('span',class_='a-profile-name')
    cust_name = []
    for j in range(len(names)):
        cust_name.append(names[j].get_text())
    cust_name.pop(0)
    cust_name.pop(0)
    return cust_name

In [3]:
def review_date():
    review_dates = soup.find_all('span',{'data-hook':'review-date'})
    review_date = []
    for j in range(len(review_dates)):
        review_date.append(review_dates[j].get_text())
#     rating.pop(0)
#     rating.pop(0)
    return review_date

In [4]:
def rating():
    ratings = soup.find_all('i',class_='review-rating')
    rating = []
    for j in range(len(ratings)):
        rating.append(ratings[j].get_text())
    rating.pop(0)
    rating.pop(0)
    return rating

In [6]:
cust_names = []
review_dates = []
ratings = []


for i in range(1,100):
    
    res = requests.get('https://www.amazon.in/Yogabar-Wholegrain-Breakfast-Muesli-Fruits/product-reviews/B07M6KZQCN/ref=cm_cr_arp_mb_paging_btm_2?pageNumber='+str(i))
    soup = BeautifulSoup(res.content,'html.parser')
    
    cust_names.extend(cust_name())
    review_dates.extend(review_date())
    ratings.extend(rating())

In [7]:
data = pd.DataFrame({'Customer Name':cust_names,
                     'Review Date':review_dates,
                     'Rating(Out of 5)':ratings})

In [8]:
len(cust_names)

863

In [9]:
len(ratings)

863

In [10]:
len(review_dates)

863

In [11]:
data

,Customer Name,Review Date,Rating(Out of 5)
0,Pooja Devlekar,Reviewed in India on 28 January 2019,5.0 out of 5 stars
1,Z,Reviewed in India on 2 February 2019,5.0 out of 5 stars
2,mum_n_kiddos,Reviewed in India on 1 March 2019,5.0 out of 5 stars
3,Shiv Shankar Ash,Reviewed in India on 16 February 2020,2.0 out of 5 stars
4,Siddharth,Reviewed in India on 24 September 2019,1.0 out of 5 stars
...,...,...,...
858,ThouzE,Reviewed in India on 6 November 2019,5.0 out of 5 stars
859,N RAMESH,Reviewed in India on 20 August 2020,5.0 out of 5 stars
860,Amazon Customer,Reviewed in India on 2 September 2019,4.0 out of 5 stars
861,Rusty,Reviewed in India on 13 May 2020,5.0 out of 5 stars
862,Swetha Gollapilli,Reviewed in India on 3 October 2019,5.0 out of 5 stars